name: personal_portfolio
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.1.2 #https://pub.dev/packages/bloc
  flutter_bloc: ^8.1.3 #https://pub.dev/packages/flutter_bloc

  # Value Equality
  equatable: ^2.0.5 #https://pub.dev/packages/equatable

  # Service Locator
  get_it: ^7.6.0 #https://pub.dev/packages/get_it

  # Navigation 2.0
  go_router: ^10.0.0 #https://pub.dev/packages/go_router

  # Responsive
  flutter_screenutil: ^5.8.4 #https://pub.dev/packages/flutter_screenutil
  # responsive_framework: ^1.1.0 #https://pub.dev/packages/responsive_framework

  #UI
  bot_toast: ^4.0.4 #https://pub.dev/packages/bot_toast

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0 #https://pub.dev/packages/intl

dev_dependencies:
  bloc_test: ^9.1.2 #https://pub.dev/packages/bloc_test
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0 #https://pub.dev/packages/mocktail
  very_good_analysis: ^5.0.0 #https://pub.dev/packages/very_good_analysis

flutter:
  uses-material-design: true
  generate: true
